version: "3.3"
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin456
      - POSTGRES_DB=users
    volumes:
      - ./gitignore/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
